### PR TITLE
replace the test bundle oci images with our ROCKs using the dev-tag on ghcr.io

### LINKED ISSUE #82: Replace the test bundle oci images with our ROCKs using the dev-tag on ghcr.io
### Enhancement Proposal

See title.

### PR DESCRIPTION
**Pull request by Abuelodelanada**
## Issue

This PR fixes #82

### CODE REVIEW

**Review by dstathis — APPROVED** [review]
Are we not using the oci-factory images on dockerhub?

**Review by PietroPasotti — APPROVED** [review]
modulo checking catalogue is published on dev (it is)

**Comment by PietroPasotti** [comment]
waiting on tests to be green before we merge

**Comment by lucabello** [comment]
Trying to re-run the tests right now; @Abuelodelanada @sed-i do we have any idea why it might be failing?

**Pull request merged**
